### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by zeinalii** [data301-2020-winter1/course-project-solo_326#1]
## High priority (must-fix)
- [ ] Where is your code? You have only uploaded screenshots of the plots. You need to also submit the code.

**Comment by naoshadsanjana** [comment]
Hi, 

All the code that I created (in Python) is in the data/processed/COVID-19 Dataset - Processed notebook. I have attached screenshots along with this message. 
![Milestone 2 Code III](https://user-images.githubusercontent.com/71401777/100161300-07f57200-2e66-11eb-8968-92528411ac50.PNG)
![Milestone 2 Code](https://user-images.githubusercontent.com/71401777/100161302-088e0880-2e66-11eb-95aa-633e2bed2190.PNG)
![Milestone 2 Code II](https://user-images.githubusercontent.com/71401777/100161303-088e0880-2e66-11eb-83f0-8ea1a40e1648.PNG)

We could also set up a time to Zoom call to figure this out? I am 100% sure that everything is fine in my Git repository?

Thanks, 
Naoshad

**Comment by zeinalii** [comment]
Why did you put a code file in the data folder? Only data files (such as CSV files) should be in data folder. Move the Jupyter file to your analysis folder.

But everything else is fine. I'll fix your mark.

Good luck. 
Amir

**Comment by naoshadsanjana** [comment]
Hi Amir, 

Sorry for the confusion! I didn't know that it was supposed to be in the Analysis folder. I just moved it to the correct folder, so hopefully everything should be fine? 

Thanks for the help, 
Naoshad

**Comment by zeinalii** [comment]
awesome.

**Comment by naoshadsanjana** [comment]
If you have any comments or suggestions for me to work on for Milestone 3, please let me know! 

Thanks!
